name: CI

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Windows User
      run: New-LocalUser -Name "newuser" -Password (ConvertTo-SecureString "StrongPassword123!" -AsPlainText -Force) -FullName "New User" -Description "Description of New User" -AccountNeverExpires

    - name: Grant Admin Rights
      run: Add-LocalGroupMember -Group "Administrators" -Member "newuser"

    # Bổ sung các bước tiếp theo tại đây nếu cần
